package Homework_7_WorkWithFiles;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

public class PlayerServiceJSON implements PlayerService {

    private static final AtomicInteger AUTOGENERATED_ID = new AtomicInteger(1);
    private static final boolean randomIsOnline = Math.random() < 0.5;
    private static final List<Player> players = new ArrayList<>();

    @Override
    public Player getPlayerById(int id) {
        for (Player player : players){
            if(player.getId() == id){
                return player;
            }
        }
        return null;
    }

    @Override
    public int createPlayer(String nickname) {
        for(Player player : players){
            if(nickname.equals(player.getNick())){
                System.out.println("Игрок с таким именем уже существует");
            }
        }
        int id = AUTOGENERATED_ID.getAndIncrement();
        Player player = new Player(id, nickname, 0, randomIsOnline);
        players.add(player);
        return player.getId();
    }

    @Override
    public Collection<Player> getPlayers() {
        return players;
    }

    // удалить игрока по id'шнику, вернет удаленного игрока
    @Override
    public Player deletePlayer(int id) {
        Player player = getPlayerById(id);
        if (player != null) {
            players.remove(player);
        }
        return player;
    }

    // добавить очков игроку. Возвращает обновленный счет
    @Override
    public int addPoints(int playerId, int points) {
        Player player = getPlayerById(playerId);
        if (player != null) {
            player.setPoints(player.getPoints() + points);
        }
        else System.out.println("Игрока с таким id не существует");
        return player.getPoints();
    }
}
